### ISSUE TITLE
Support Swagger's "additionalProperties" keyword for object with dynamic keys

### ISSUE THREAD

**Issue by GabriMcNab** [musement/types-generator#22]
In an OpenAPI document, when an object has some dynamic keys, it's declared like so:

```
someObject:
  type: object
  additionalProperties:
    type: string
```

Currently, the [additionalProperties](https://swagger.io/docs/specification/data-models/dictionaries/) keyword is ignored, and the Typescript type is generated in this way:

`someObject: {}`

If you are using `typescript-eslint` > [v5.0.0](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v5.0.0), this will raise an error, because the `empty object literal` syntax [is banned](https://github.com/typescript-eslint/typescript-eslint/blob/v5.4.0/packages/eslint-plugin/docs/rules/ban-types.md), as it is considered unsafe. Instead we should use:

`someObject: Record<string, string>`

In addition to the example shown above, there are other use cases for `additionalProperties`:

```
someObject:
  type: object
  additionalProperties: true
```

If the dictionary values can be of any type (aka free-form object) --> `Record<string, unknown>`

```
someObject:
  type: object
  additionalProperties:
    $ref: '#/components/schemas/Message'
```

Instead of using an inline schema, additionalProperties can $ref another schema

```
someObject:
  type: object
  properties:
    default:
      type: string
  required:
    - default
  additionalProperties:
    type: string
```

When a dictionary has some fixed properties, and some dynamic ones.
